spring:
  datasource:  # 数据库配置
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8 # 数据库连接地址
    driver-class-name: com.mysql.cj.jdbc.Driver   # 数据库驱动
    username: root                                # 用户名
    password: 1234                              # 密码
server:
  port: 8181

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

